# Generated by Django 3.1.1 on 2020-09-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('math', models.CharField(max_length=30)),
                ('english', models.CharField(max_length=30)),
                ('science', models.CharField(max_length=30)),
            ],
        ),
    ]
