# Generated by Django 3.1.1 on 2020-09-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0002_todo_todogroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='url',
        ),
        migrations.AddField(
            model_name='todo',
            name='del_yn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(default='end', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todogroup',
            name='del_yn',
            field=models.BooleanField(default=False),
        ),
    ]
